baseURL = "https://main--uds.netlify.app/"
enableRobotsTXT = true
enableGitInfo = true

# Set uglyURLs & relativeURLs for hugo to build local offline pages in public/
# When these are set `npm start` will no longer host functioning webpages. Instead
#   use `npm run build` to construct the offline public/ directory 
relativeURLs = false
uglyURLs     = false

[[module.mounts]]
    source = "content/en"
    target = "content"

[[module.mounts]]
    source = "content/en/redesigned-lamp"
    target = "content/core/identity"

[module]
    proxy = "direct"

    [[module.imports]]
        path = "github.com/defenseunicorns/defense-unicorns-hugo-theme"

    [[module.imports]]
        path = "github.com/defenseunicorns/defense-unicorns-hugo-theme/dependencies"

[languages.en]
    languageName = "English"

    [languages.en.params]
        title = "UDS"
        description = "Unicorn Delivery Service"

[params]
    _merge = 'deep' # Use theme defaults
    copyright = "Defense Unicorns"
    github_repo = "https://github.com/defenseunicorns/uds-core"
    github_project_repo = "https://github.com/defenseunicorns/uds-core"
    github_subdir = "content/en"
    archived_version = false
    version = "v0.1.0" 

[params.ui]
    navbar_logo = "img/uds-logo.svg" # The product logo on the navbar

[[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/defenseunicorns/uds-core"
    icon = "fa-brands fa-github"
    desc = ""

## The following merge in theme defaults from: https://github.com/defenseunicorns/defense-unicorns-hugo-theme/tree/main/config/_default
[markup]
    _merge = 'shallow'

[outputs]
    _merge = 'shallow'

[imaging]
    _merge = 'shallow'

[taxonomies]
    _merge = 'shallow'
