tasks:
  - name: gitlab-test-bundle
    description: Create the UDS bundle with Gitlab and its dependencies
    actions:
      - task: dependency-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: dependency-package
    description: Create the Minio, PostgreSQL, and Redis Dependency Zarf Packages
    actions:
      - cmd: uds zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
