image:
  registry: docker.io
  repository: grafana/promtail
  tag: 3.0.0
sidecar:
  configReloader:
    image:
      registry: ghcr.io
      repository: jimmidyson/configmap-reload
      tag: v0.12.0
