name: Build and Test

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.get-node-version.outputs.node-version }}
    steps:
      - id: get-node-version
        uses: defenseunicorns/website-commons/.github/actions/get-node-version@main
      - uses: defenseunicorns/website-commons/.github/actions/npm-setup@main
        with:
          node-version: ${{ steps.get-node-version.outputs.node-version }}