name: Netlify Deploy

on:
  pull_request_target:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  push-to-deploy-branch:
    if: >
      github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'chore(main): release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          ref: 'main'

      - name: Checkout tag
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          ref: ${{ github.ref }}

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create or reset deploy branch
        run: |
          git fetch
          git branch -D netlify-deploy || true  # Delete the branch if it exists
          git checkout -b netlify-deploy       # Create a new branch from the tag

      - name: Push to deploy branch
        run: |
          git push -f origin netlify-deploy  # Force-push to the branch
