name: Create Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
